configuration:
  services:
  - blur-faces:
      cluster: "raspi_cluster"
      cpu: 0.9
      memory_mb: 1024
      image_x86: scrapjack/blurry-faces-modded:stable
      image_ARM64: ghcr.io/srisco/blurry-faces-arm64
      script: bash-scripts/blurry-faces.sh
      input_bucket: input-videos
      output_buckets:
        - path: blurred-images
          prefix: [ ]
          suffix: [ ]
  - mask-detector:
      cluster: "vm_cluster"
      cpu: 0.9
      memory_mb: 1024
      image_x86: scrapjack/mask-detector-modded:stable
      script: bash-scripts/mask-detector.sh
      input_bucket: blurred-images
      output_buckets:
        - path: results
          prefix: [ ]
          suffix: [ ]
  layers:
    - layer1:
        name: Edge Layer
        clusters:
          - raspi_cluster:
              oscarcli_alias: "oscar-raspi"
              minio_alias: "minio-raspi"
              ip_address: 158.42.105.64
              port: 10022
              username: "grycap"
              architecture: ARM64
              active_nodes: 1
              total_nodes: 3
              max_cpu_cores: 4.0
              max_memory_mb: 4096
    - layer2:
        name: Cloud Layer
        clusters:
          - vm_cluster:
              oscarcli_alias: "oscar-vm"
              minio_alias: "minio-vm"
              ip_address: 158.42.105.149
              port: 10022
              username: "aisprint"
              architecture: x86
              active_nodes: [3, 4]
              total_nodes: 8
              max_cpu_cores: 4.0
              max_memory_mb: 8192
  input_files:
    filename: "Test-Video.mp4"
    number_of_files: 1
    batch_size: 2
    distribution: deterministic
    inter_upload_time: 10
  run:
    name: "heterogeneous-test"
    description: ""
    repetitions: 3
    cooldown_time: 60
    parallelism: [1, 2, 4, 7, 8, 32]
  other:
    time_correction: 1
    test_single_components: True
    debug: False
