functions:
  oscar:
  - oscar-vm:
      cpu: '0.9'
      image: scrapjack/mask-detector-modded:stable
      input:
      - path: dead-start
        storage_provider: minio.default
      memory: 1638Mi
      name: mask-detector
      output:
      - path: results
        prefix: []
        storage_provider: minio.minio-vm
        suffix: []
      script: bash-scripts/mask-detector.sh
storage_providers:
  minio:
    minio-vm:
      access_key: minio
      endpoint: https://minio.quirky-kowalevski6.im.grycap.net
      region: us-east-1
      secret_key: minio-aisprint-2022
