functions:
  oscar:
  - oscar-vm:
      cpu: '0.9'
      image: scrapjack/mask-detector-modded:stable
      input:
      - path: dead-start
        storage_provider: minio.default
      memory: 1024Mi
      name: mask-detector
      output:
      - path: results
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/mask-detector.sh
