functions:
  oscar:
  - oscar-raspi:
      cpu: '1.9'
      image: ghcr.io/srisco/blurry-faces-arm64
      input:
      - path: input-videos
        storage_provider: minio.default
      memory: 1984Mi
      name: blur-faces
      output:
      - path: blurred-images
        prefix: []
        storage_provider: minio.vm_cluster
        suffix: []
      script: bash-scripts/blurry-faces.sh
  - oscar-vm:
      cpu: '1.9'
      image: scrapjack/mask-detector-modded:stable
      input:
      - path: blurred-images
        storage_provider: minio.default
      memory: 4032Mi
      name: mask-detector
      output:
      - path: results
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/mask-detector.sh
storage_providers:
  minio:
    raspi_cluster:
      access_key: minio
      endpoint: https://minio.graspi.im.grycap.net
      region: us-east-1
      secret_key: minio-aisprint-2021
    vm_cluster:
      access_key: minio
      endpoint: https://minio.quirky-kowalevski6.im.grycap.net
      region: us-east-1
      secret_key: minio-aisprint-2022
