functions:
  oscar:
  - oscar-raspi:
      cpu: '3.9'
      image: ghcr.io/srisco/blurry-faces-arm64
      input:
      - path: dead-start
        storage_provider: minio.default
      memory: 3276Mi
      name: blur-faces
      output:
      - path: blurred-images
        prefix: []
        storage_provider: minio.minio-vm
        suffix: []
      script: bash-scripts/blurry-faces.sh
storage_providers:
  minio:
    minio-raspi:
      access_key: minio
      endpoint: https://minio.graspi.im.grycap.net
      region: us-east-1
      secret_key: minio-aisprint-2021
    minio-vm:
      access_key: minio
      endpoint: https://minio.quirky-kowalevski6.im.grycap.net
      region: us-east-1
      secret_key: minio-aisprint-2022
