functions:
  oscar:
  - oscar-vm:
      cpu: '0.9'
      image: linuxserver/ffmpeg
      input:
      - path: input-audio
        storage_provider: minio.default
      memory: 1024Mi
      name: ffmpeg2
      output:
      - path: output-audio
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/ffmpeg2.sh
  - oscar-vm:
      cpu: '0.9'
      image: scrapjack/deepspeech:stable
      input:
      - path: output-audio
        storage_provider: minio.default
      memory: 1024Mi
      name: deepspeech
      output:
      - path: output-text
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/deepspeech.sh
