functions:
  oscar:
  - oscar-vm:
      cpu: '1.9'
      image: scrapjack/blurry-faces-modded:stable
      input:
      - path: input-videos
        storage_provider: minio.default
      memory: 1024Mi
      name: blur-faces
      output:
      - path: blurred-images
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/blurry-faces.sh
  - oscar-vm:
      cpu: '1.9'
      image: scrapjack/mask-detector-modded:stable
      input:
      - path: blurred-images
        storage_provider: minio.default
      memory: 1024Mi
      name: mask-detector
      output:
      - path: results
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/mask-detector.sh
