functions:
  oscar:
  - oscar-vm:
      cpu: '3.9'
      image: ubuntu:20.04
      input:
      - path: dead-start
        storage_provider: minio.default
      memory: 1024Mi
      name: ubuntu
      output:
      - path: results
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/ubuntu.sh
