functions:
  oscar:
  - oscar-vm:
      cpu: '0.9'
      image: linuxserver/ffmpeg:amd64-version-4.4-cli
      input:
      - path: dead-start
        storage_provider: minio.default
      memory: 1024Mi
      name: ffmpeg0
      output:
      - path: input-librosa
        prefix: []
        storage_provider: minio.default
        suffix: []
      script: bash-scripts/ffmpeg0.sh
